// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteProject(ctx context.Context, id int64) (int64, error)
	DeleteTask(ctx context.Context, id int64) (int64, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTasksByProject(ctx context.Context, projectID int64) ([]Task, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
